name: Setup Windows

description: Set up for windows jobs

inputs:
  cuda-version:
    description: which cuda version to install, 'cpu' for none
    required: false
    default: 'cpu'

runs:
  using: composite
  steps:
    - name: Hello World
      shell: powershell
      run: |
        Hello world!